import '@/app/globals.css'
import { Inter } from 'next/font/google'
import {NextUIProvider} from "@nextui-org/react";
import Navbar from './components/Navbar'
import Footer from './components/Footer'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='flex justify-center items-center'>
        <NextUIProvider>
          <Navbar></Navbar>
          {children}
          <Footer></Footer>
        </NextUIProvider>
      </body>
    </html>
  )
}
